### ISSUE TITLE
login timeout

### ISSUE THREAD

**Issue by runmain** [arthurkiller/electronic-QQ#13]
when to resolve login timeout problem after long time no operations

**Comment by arthurkiller** [comment]
I will take care of this, maybe next version.Really busy these days

Best regards 
✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee

**Comment by arthurkiller** [comment]
@runmain  Did it only happen when you have no action on it for few hours?
