### ISSUE TITLE
when run npm start ,failed at /electron/index.js

### ISSUE THREAD

**Issue by ggchang** [arthurkiller/electronic-QQ#14]
# failed log:
> electronic-QQ@0.1.0 start /home/ggchang/下载/electronic-QQ-0.0.2
> electron src/main.js

/home/ggchang/下载/electronic-QQ-0.0.2/node_modules/electron/index.js:9
  throw new Error('Electron failed to install correctly, please delete node_modules/' + path.basename(__dirname) + ' and try installing again')
  ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at Object.<anonymous> (/home/ggchang/下载/electronic-QQ-0.0.2/node_modules/electron/index.js:9:9)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ggchang/下载/electronic-QQ-0.0.2/node_modules/electron/cli.js:3:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
npm ERR! Linux 4.8.0-39-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! electronic-QQ@0.1.0 start: `electron src/main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electronic-QQ@0.1.0 start script 'electron src/main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electronic-QQ package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron src/main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electronic-QQ
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electronic-QQ
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ggchang/下载/electronic-QQ-0.0.2/npm-debug.log

# how to fix ?

**Comment by arthurkiller** [comment]
@ggchang  You'd try the electron to run this
nmp install the electron for global use

```
cd electronic-QQ
./electron .
```
