### ISSUE TITLE
最好能加上安装说明，对于linux新手来说是大福音

### ISSUE THREAD

**Issue by SZooo** [arthurkiller/electronic-QQ#17]

**Comment by arthurkiller** [comment]
@SZooo  好的，最近太忙了，一直没时间搞，目前实在是太原始了。

**Comment by SZooo** [comment]
我也想参与这个项目，但是没接触过node.js，无从下手

**Comment by arthurkiller** [comment]
@SZooo 其实我是后端做得多，c c++ go，js 我也是会一点点，框架什么的确实不太懂，之前在学，还没学明白，最近的工作比较紧，一直没时间搞

**Comment by arthurkiller** [comment]
@SZooo 一起研究可以，我等下建立一个gitter，大家可以一起交流，学习
