### ISSUE TITLE
这不就是webQQ吗

### ISSUE THREAD

**Issue by wszqkzqk** [arthurkiller/electronic-QQ#21]
还以为是自己抓取api做的。。。

**Comment by arthurkiller** [comment]
抱歉，我不会搞前端，水平有限，自己做不出来。有兴趣可以贡献pr

Best regards 
✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee

**Comment by wszqkzqk** [comment]
@arthurkiller 我现在只搞搞wine QQ

**Comment by wszqkzqk** [comment]
@arthurkiller
可以看看我的项目：https://github.com/wszqkzqk/wszqkzqk-deepin-wine-tim-arch

**Comment by arthurkiller** [comment]
嗯，不错。不过你可以看下这个项目的readme。目的就是不要wine 或者任何类似wine的东西，原声qq。后面会想想办法找找api，实现一些简单的功能。不过应该整体还是基于smart qq

Best regards 
✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee
