### ISSUE TITLE
Blank page with header "Smart QQ" right after QR code login

### ISSUE THREAD

**Issue by renxida** [arthurkiller/electronic-QQ#22]
What I did:
```
npm install
npm build:linux
cd dist
./Electronic-QQ
```
and used android qq to scan qr code to login (password login does not work because the 滑动拼图验证码 is displayed incompletely).

What I expect: some kind of interface.

What I got: page with title "Smart QQ" and nothing else.

[PS:Would you prefer me to speak English or Chinese here?]

**Comment by renxida** [comment]
System:
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.10
Release:	16.10
Codename:	yakkety
```
Window manager: xmonad
(electronic-WeChat works fine for me)

**Comment by arthurkiller** [comment]
I thing this issues has been fixed, since the url changed.

If this problem still occurred again, you can reopen this issue freely. @renxida
