### ISSUE TITLE
How do I open the qq

### ISSUE THREAD

**Issue by Giotto110** [arthurkiller/electronic-QQ#26]
How to open after download package decompression

**Comment by arthurkiller** [comment]
What you mean?

**Comment by a807966224** [comment]
sorry, can not open web qq with electronicqq, on the welcome page it stop!!! and it does not work with i do something

**Comment by dtlvhyy** [comment]
I clicked the "立即体验" button ,but nothing happened,it seems that the web qq doesn't work any more.

**Comment by arthurkiller** [comment]
Get it.

**Comment by a807966224** [comment]
If you have solved it，Please let us know，Thanks

**Comment by djndl1** [comment]
I tried to change /src/common.js and it worked, it has the same UI as smartqq though.
`Common.WEB_QQ= 'http://web2.qq.com/';`

**Comment by a807966224** [comment]
6666 i try too,   hahah

**Comment by arthurkiller** [comment]
@djndl1 thx for your contribute, I will try this

**Comment by arthurkiller** [comment]
Fixed in fc3886d. @djndl1 Thx for your contribute.
